# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9a8e9533bfac49c6fddfb3e43833f9e531eaceb2d81add30fc849e330a5fc1132f81e6f328e543484f213f4c0a703c2fa1fcce0a19cef10682de818d4a8412b3

test:
  secret_key_base: cece753269aa2cc2c9fcd9dfe397483588e426b70a910a6408c1b06f5139ab1dec768b44637bc8f2bea2a600a4857999412146c187f66c341cc2dca58323e60a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
